env: 
  global: 
    - CC_TEST_REPORTER_ID=09d9d33de8bab9eb32c5cc5967ea799ec8fe91974f087827e17033397
language: node_js
node_js: 
 - node
before_script: 
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-1-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
 - make lint 
after_script: 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
